name: Generate release-artifacts

# on events
on:
  push:
    tags:
        - 'v*'
  pull_request:
    paths:
      - '**/.github/**/*'

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Checkout the repository
        uses: actions/checkout@v2
      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: '^1.17.0' # The Go version to download (if necessary) and use.
      # - run: |
      #     go vet .
      - name: Generate build files
        uses: adamruzicka/go-cross-build@1.19-alpine3.18
        with:
            platforms: 'linux/amd64'
            package: '.'
            name: 'yggdrasil-worker-forwarder-${{ steps.tagName.outputs.tag }}'
            compress: 'true'
            dest: 'dist'
      - name: Generate distribution tarball
        run: |
          make distribution-tarball
          sudo mv *.tar.gz dist/
        env:
          VERSION: '${{ steps.tagName.outputs.tag }}'
      - name: Upload binaries to release
        if: "${{ steps.tagName.outputs.tag != '' }}" # tag will be empty on pull requests, no publishing needed
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
